### ISSUE TITLE
新手请教 

### ISSUE THREAD

**Issue by home-z** [songjhh/songjhh_blog#1]
![image](https://user-images.githubusercontent.com/24502855/37208733-679c3874-23dd-11e8-87bc-63ce2732e46d.png)
![image](https://user-images.githubusercontent.com/24502855/37208888-01df3878-23de-11e8-85a4-b4c6f0d7ebe1.png)

 
请问是我路路径写错了吗？我把路径最后的index.jsp换成/admin/checkUserList也是404

**Comment by songjhh** [comment]
访问控制器看看能不能访问，打个断点
检查下项目名，检查下端口号

________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

发件人： home-z<mailto:notifications@github.com>
发送时间： 2018-03-09 21:07:38
收件人：  songjhh/songjhh_blog<mailto:songjhh_blog@noreply.github.com>
抄送：  Subscribed<mailto:subscribed@noreply.github.com>
主题： [songjhh/songjhh_blog] 新手请教 (#1)

[image]<https://user-images.githubusercontent.com/24502855/37208733-679c3874-23dd-11e8-87bc-63ce2732e46d.png>

请问是我路路径写错了吗？我把路径最后的index.jsp换成/admin/checkUserList也是404

**Comment by home-z** [comment]
断点我也打了，在图2的42行，以bug模式启动服务器但没有触发debug模式说明路径没有进到这里，但路径和端口我是一再确认和复制过来的，且本地访问tomcat成功。

**Comment by songjhh** [comment]
检查songjhh_blog服务名和端口8088
检查服务是否正常起起来
404只能是地址错误

**Comment by home-z** [comment]
Ok Thanks
